spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xh2018//
    url: jdbc:mysql://hadoop1:3306/db02?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: hadoop1
    port: 6379
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html


#server:
#  port: 80

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis.xml








